# DC4U Configuration File
# Version 2.0.0

# General settings
output_directory: "./output"
log_level: "INFO"
jurisdiction: "singapore"
template_directory: "./templates"
default_format: "PDF"
date_format: "DD/MM/YYYY"
timezone: "Asia/Singapore"

# Singapore-specific settings
singapore:
  court_name: "State Courts of Singapore"
  legal_act: "Criminal Procedure Code 2010"
  act_chapter: "CHAPTER 68"
  act_edition: "REVISED EDITION 2012"
  sections: "SECTIONS 123-125"

# UK-specific settings (for future use)
uk:
  court_name: "Magistrates Court"
  legal_act: "Criminal Justice Act 2003"
  act_chapter: "CHAPTER 44"
  act_edition: "REVISED EDITION 2020"
  sections: "SECTIONS 1-10"

# Output format settings
formats:
  pdf:
    font_family: "Times-Roman"
    font_size: 12
    margins:
      top: 50
      bottom: 50
      left: 50
      right: 50
  
  html:
    css_file: "templates/css/charge.css"
    include_bootstrap: false
  
  txt:
    line_width: 80
    encoding: "UTF-8"
